sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fazale/docker-react -f ./sample/dockerfile ./sample
  - docker build -t fazale/docker-node -f ./backend/dockerfile ./backend




# script:
#   - docker run -e CI=true fazale/docker-react npm run test

after_success:
  - docker build -t fazale/single-client ./sample

  - docker build -t fazale/single-node ./backend

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push fazale/single-client